export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "./globals.css"; //to enable tailwind
import Mainfooter from "./Mainfooter";
import MainHeader from "./mainheader";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MainHeader />
        {children}
        <Mainfooter />
      </body>
    </html>
  );
}
